import { IsString, IsNotEmpty, IsOptional, IsObject } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class SendWidgetMessageDto {
  @ApiProperty({
    description: 'ID of the chatbot',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @IsString()
  @IsNotEmpty()
  botId: string;

  @ApiProperty({
    description: 'Message content from the user',
    example: 'Hello, I need help with my order',
  })
  @IsString()
  @IsNotEmpty()
  message: string;

  @ApiProperty({
    description: 'Optional conversation ID (if continuing existing conversation)',
    example: '123e4567-e89b-12d3-a456-426614174000',
    required: false,
  })
  @IsString()
  @IsOptional()
  conversationId?: string;

  @ApiProperty({
    description: 'External user ID (generated by widget, stored in localStorage)',
    example: 'widget-user-abc123',
  })
  @IsString()
  @IsNotEmpty()
  externalUserId: string;

  @ApiProperty({
    description: 'Optional metadata (user agent, page URL, etc.)',
    example: { userAgent: 'Mozilla/5.0...', pageUrl: 'https://example.com' },
    required: false,
  })
  @IsObject()
  @IsOptional()
  metadata?: Record<string, any>;
}
