import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { BillingService } from '../billing/billing.service';
import { CacheService } from '../../common/cache/cache.service';
import { CreateChatbotDto } from './dto/create-chatbot.dto';
import { UpdateChatbotDto } from './dto/update-chatbot.dto';
import { PaginationDto, PaginatedResponseDto, getPaginationParams } from '../../common/dto/pagination.dto';
import { AI_PROVIDERS, AI_MODELS, VALID_PROVIDERS } from '../../common/constants/ai-constants';

@Injectable()
export class ChatbotsService {
  constructor(
    private prisma: PrismaService,
    private billingService: BillingService,
    private cacheService: CacheService,
  ) { }

  /**
   * Validate AI provider and model configuration
   */
  private validateAIConfiguration(aiProvider: string, aiModel: string): void {
    if (!VALID_PROVIDERS.includes(aiProvider.toLowerCase() as any)) {
      throw new BadRequestException(
        `Invalid AI provider "${aiProvider}". Valid providers are: ${VALID_PROVIDERS.join(', ')}`
      );
    }

    const validModels = AI_MODELS[aiProvider.toLowerCase() as keyof typeof AI_MODELS];
    if (validModels && !(validModels as readonly string[]).includes(aiModel)) {
      throw new BadRequestException(
        `Invalid model "${aiModel}" for provider "${aiProvider}". Valid models are: ${validModels.join(', ')}`
      );
    }
  }

  async create(customerId: string, createChatbotDto: CreateChatbotDto) {
    // Validate chatbot limit before creating
    await this.billingService.validateChatbotLimit(customerId);

    // Validate AI provider and model configuration
    this.validateAIConfiguration(createChatbotDto.aiProvider, createChatbotDto.aiModel);

    // Validate AI provider is allowed in customer's plan
    await this.billingService.validateAIProvider(
      customerId,
      createChatbotDto.aiProvider,
    );

    // Verify customer exists
    const customer = await this.prisma.customer.findUnique({
      where: { id: customerId },
    });

    if (!customer) {
      throw new NotFoundException(`Customer with ID ${customerId} not found`);
    }

    // If knowledgeBaseId is provided, verify it exists and belongs to customer
    if (createChatbotDto.knowledgeBaseId) {
      const knowledgeBase = await this.prisma.knowledgeBase.findFirst({
        where: {
          id: createChatbotDto.knowledgeBaseId,
          customerId,
        },
      });

      if (!knowledgeBase) {
        throw new BadRequestException(
          'Knowledge base not found or does not belong to customer',
        );
      }
    }

    // Create chatbot with UUID auto-generated by Prisma
    const chatbot = await this.prisma.chatbot.create({
      data: {
        customerId,
        name: createChatbotDto.name,
        description: createChatbotDto.description,
        aiProvider: createChatbotDto.aiProvider,
        aiModel: createChatbotDto.aiModel,
        aiConfig: createChatbotDto.aiConfig || {},
        systemPrompt: createChatbotDto.systemPrompt,
        knowledgeBaseId: createChatbotDto.knowledgeBaseId,
        isActive: createChatbotDto.isActive !== undefined ? createChatbotDto.isActive : true,
      },
      include: {
        customer: {
          include: {
            user: {
              select: {
                id: true,
                email: true,
                name: true,
              },
            },
          },
        },
        knowledgeBase: {
          select: {
            id: true,
            name: true,
            description: true,
          },
        },
      },
    });

    // Invalidate cache for customer's chatbot list
    await this.cacheService.delPattern(`chatbots:customer:${customerId}:*`);

    return chatbot;
  }

  async findAll(customerId: string, paginationDto: PaginationDto = {}) {
    // Verify customer exists
    const customer = await this.prisma.customer.findUnique({
      where: { id: customerId },
    });

    if (!customer) {
      throw new NotFoundException(`Customer with ID ${customerId} not found`);
    }

    const { page = 1, limit = 10 } = paginationDto;
    const { skip, take } = getPaginationParams(page, limit);

    // Try to get from cache first
    const cacheKey = `chatbots:customer:${customerId}:page:${page}:limit:${limit}`;
    const cached = await this.cacheService.get<PaginatedResponseDto<any>>(cacheKey);

    if (cached) {
      return cached;
    }

    // Get total count for pagination
    const total = await this.prisma.chatbot.count({
      where: { customerId },
    });

    // Return only chatbots belonging to this customer with pagination
    const chatbots = await this.prisma.chatbot.findMany({
      where: { customerId },
      include: {
        knowledgeBase: {
          select: {
            id: true,
            name: true,
            description: true,
          },
        },
        widgetSettings: {
          select: {
            id: true,
            theme: true,
            primaryColor: true,
            position: true,
          },
        },
        whatsappCloudAccount: {
          select: {
            id: true,
            phoneNumberId: true,
            isActive: true,
          },
        },
        whatsappQRSession: {
          select: {
            id: true,
            sessionId: true,
            status: true,
          },
        },
        _count: {
          select: {
            conversations: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
      skip,
      take,
    });

    const result = new PaginatedResponseDto(chatbots, total, page, limit);

    // Cache for 5 minutes
    await this.cacheService.set(cacheKey, result, 300);

    return result;
  }

  async findOne(id: string, customerId: string) {
    // Try to get from cache first
    const cacheKey = `chatbot:${id}`;
    const cached = await this.cacheService.get<any>(cacheKey);

    if (cached && cached.customerId === customerId) {
      return cached;
    }

    const chatbot = await this.prisma.chatbot.findFirst({
      where: {
        id,
        customerId,
      },
      include: {
        customer: {
          include: {
            user: {
              select: {
                id: true,
                email: true,
                name: true,
              },
            },
            subscription: {
              include: {
                plan: true,
              },
            },
          },
        },
        knowledgeBase: {
          select: {
            id: true,
            name: true,
            description: true,
          },
        },
        widgetSettings: true,
        whatsappCloudAccount: true,
        whatsappQRSession: true,
        conversations: {
          select: {
            id: true,
            externalUserId: true,
            channel: true,
            status: true,
            lastMessageAt: true,
            createdAt: true,
          },
          orderBy: {
            lastMessageAt: 'desc',
          },
          take: 10,
        },
        _count: {
          select: {
            conversations: true,
          },
        },
      },
    });

    if (!chatbot) {
      throw new NotFoundException(
        `Chatbot with ID ${id} not found or does not belong to customer`,
      );
    }

    // Cache for 10 minutes
    await this.cacheService.set(cacheKey, chatbot, 600);

    return chatbot;
  }

  async update(id: string, customerId: string, updateChatbotDto: UpdateChatbotDto) {
    // Verify chatbot exists and belongs to customer
    const existingChatbot = await this.prisma.chatbot.findFirst({
      where: {
        id,
        customerId,
      },
    });

    if (!existingChatbot) {
      throw new NotFoundException(
        `Chatbot with ID ${id} not found or does not belong to customer`,
      );
    }

    // Validate AI configuration if provider or model is being changed
    const newProvider = updateChatbotDto.aiProvider || existingChatbot.aiProvider;
    const newModel = updateChatbotDto.aiModel || existingChatbot.aiModel;

    if (updateChatbotDto.aiProvider || updateChatbotDto.aiModel) {
      this.validateAIConfiguration(newProvider, newModel);
    }

    // If AI provider is being changed, validate it's allowed in customer's plan
    if (updateChatbotDto.aiProvider && updateChatbotDto.aiProvider !== existingChatbot.aiProvider) {
      await this.billingService.validateAIProvider(
        customerId,
        updateChatbotDto.aiProvider,
      );
    }

    // If knowledgeBaseId is being changed, verify it exists and belongs to customer
    if (updateChatbotDto.knowledgeBaseId) {
      const knowledgeBase = await this.prisma.knowledgeBase.findFirst({
        where: {
          id: updateChatbotDto.knowledgeBaseId,
          customerId,
        },
      });

      if (!knowledgeBase) {
        throw new BadRequestException(
          'Knowledge base not found or does not belong to customer',
        );
      }
    }

    // Update chatbot
    const chatbot = await this.prisma.chatbot.update({
      where: { id },
      data: {
        name: updateChatbotDto.name,
        description: updateChatbotDto.description,
        aiProvider: updateChatbotDto.aiProvider,
        aiModel: updateChatbotDto.aiModel,
        aiConfig: updateChatbotDto.aiConfig,
        systemPrompt: updateChatbotDto.systemPrompt,
        knowledgeBaseId: updateChatbotDto.knowledgeBaseId,
        isActive: updateChatbotDto.isActive,
      },
      include: {
        customer: {
          include: {
            user: {
              select: {
                id: true,
                email: true,
                name: true,
              },
            },
          },
        },
        knowledgeBase: {
          select: {
            id: true,
            name: true,
            description: true,
          },
        },
      },
    });

    // Invalidate cache
    await this.cacheService.del(`chatbot:${id}`);
    await this.cacheService.delPattern(`chatbots:customer:${customerId}:*`);

    return chatbot;
  }

  async remove(id: string, customerId: string) {
    // Verify chatbot exists and belongs to customer
    const existingChatbot = await this.prisma.chatbot.findFirst({
      where: {
        id,
        customerId,
      },
    });

    if (!existingChatbot) {
      throw new NotFoundException(
        `Chatbot with ID ${id} not found or does not belong to customer`,
      );
    }

    // Delete chatbot (cascade will delete related records)
    await this.prisma.chatbot.delete({
      where: { id },
    });

    // Invalidate cache
    await this.cacheService.del(`chatbot:${id}`);
    await this.cacheService.delPattern(`chatbots:customer:${customerId}:*`);

    return { message: 'Chatbot deleted successfully' };
  }

  async getStats(id: string, customerId: string) {
    // Verify chatbot exists and belongs to customer
    const chatbot = await this.prisma.chatbot.findFirst({
      where: {
        id,
        customerId,
      },
    });

    if (!chatbot) {
      throw new NotFoundException(
        `Chatbot with ID ${id} not found or does not belong to customer`,
      );
    }

    // Get conversation stats
    const totalConversations = await this.prisma.conversation.count({
      where: { chatbotId: id },
    });

    const activeConversations = await this.prisma.conversation.count({
      where: {
        chatbotId: id,
        status: 'ACTIVE',
      },
    });

    // Get message stats
    const totalMessages = await this.prisma.message.count({
      where: {
        conversation: {
          chatbotId: id,
        },
      },
    });

    const userMessages = await this.prisma.message.count({
      where: {
        conversation: {
          chatbotId: id,
        },
        role: 'USER',
      },
    });

    const assistantMessages = await this.prisma.message.count({
      where: {
        conversation: {
          chatbotId: id,
        },
        role: 'ASSISTANT',
      },
    });

    // Get messages by channel
    const messagesByChannel = await this.prisma.conversation.groupBy({
      by: ['channel'],
      where: { chatbotId: id },
      _count: {
        id: true,
      },
    });

    return {
      chatbotId: id,
      conversations: {
        total: totalConversations,
        active: activeConversations,
        closed: totalConversations - activeConversations,
      },
      messages: {
        total: totalMessages,
        user: userMessages,
        assistant: assistantMessages,
      },
      channels: messagesByChannel.reduce((acc, item) => {
        acc[item.channel] = item._count.id;
        return acc;
      }, {} as Record<string, number>),
    };
  }
}
